#!/bin/sh

# Set these paths appropriately

BIN=/home/garciaflores/code/java/platanne/code/erwan/tools/TreeTagger/bin
CMD=/home/garciaflores/code/java/platanne/code/erwan/tools/TreeTagger/cmd
LIB=/home/garciaflores/code/java/platanne/code/erwan/tools/TreeTagger/lib

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/tokenize.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/german-abbreviations
PARFILE=${LIB}/german.par
LEXFILE=${LIB}/german-lexicon.txt
FILTER=${CMD}/filter-german-tags

$TOKENIZER -a $ABBR_LIST $* |
# external lexicon lookup
perl $CMD/lookup.perl $LEXFILE |
# tagging
$TAGGER $OPTIONS $PARFILE  | 
# error correction
$FILTER
